### ISSUE TITLE
setThreshold not working after initialization

### ISSUE THREAD

**Issue by ignasurba** [adafruit/Adafruit_Python_MPR121#6]
There is an issue with the setThreshold usage, the following code does not set the thresholds:
```
cap = MPR121.MPR121()
cap.begin():
cap.set_thresholds(60, 30)
```

Changing the MPR121.py in the _reset function:
```
# Set threshold for touch and release to default values.
self.set_thresholds(60, 30)
```
changes the thresholds.

It has to do with the MPR121 being in "Run" mode.
Issue was described in a topic: [https://forums.adafruit.com/viewtopic.php?f=22&t=87742](url)

**Comment by kattni** [comment]
This library is no longer supported. We are only supporting the use of CircuitPython libraries through [Adafruit Blinka](https://github.com/adafruit/Adafruit_Blinka). Please see the [Adafruit CircuitPython MPR121 library](https://github.com/adafruit/Adafruit_CircuitPython_MPR121).

This issue was fixed in the CircuitPython library: https://github.com/adafruit/Adafruit_CircuitPython_MPR121/issues/11 and https://github.com/adafruit/Adafruit_CircuitPython_MPR121/pull/13
